const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const root=path.resolve(__dirname,'..'),js=fs.readFileSync(path.join(root,'contractor','contractor.js'),'utf8'),css=fs.readFileSync(path.join(root,'contractor','contractor.css'),'utf8'),migration=fs.readFileSync(path.join(root,'supabase','migrations','021_contractor_portal_foundation.sql'),'utf8'),admin=fs.readFileSync(path.join(root,'admin','recruitment-operations.js'),'utf8');
const pages=['index','vacancies','applications','interviews','joinings','profile','assignments'].map(n=>fs.readFileSync(path.join(root,'contractor',`${n}.html`),'utf8'));
test('contractor portal uses only narrow RPCs',()=>{assert.match(js,/get_contractor_portal_context/);assert.match(js,/manage_contractor_portal_vacancy/);assert.doesNotMatch(js,/\.from\s*\(/)});
test('separate contractor navigation is present',()=>pages.forEach(s=>{assert.match(s,/CONTRACTOR PORTAL/);assert.match(s,/My Vacancies/);assert.doesNotMatch(s,/Staff Management/)}));
test('session boundary is server resolved',()=>{assert.match(js,/client\.rpc\(name,args\)/);assert.match(js,/This login does not have Contractor Portal access/)});
test('dashboard exposes contractor-scoped metrics',()=>['draft_vacancies','under_review','approved_active','applications','interviews','joined'].forEach(k=>assert.match(pages[0],new RegExp(k))));
test('vacancy form has structured canonical fields',()=>['clientName','jobRole','jobLocation','requiredHeadcount','qualification','itiTrade','experienceRequirement','salaryMin','expectedJoiningDate'].forEach(k=>assert.match(pages[1],new RegExp(k))));
test('contractor cannot choose approval state',()=>{assert.doesNotMatch(pages[1],/name="(submissionStatus|requirementStage|visibility)"/);assert.match(js,/submitted for review\. It is not published to candidates/)});
test('correction and resubmission states are constrained',()=>{assert.match(js,/\['draft','correction_required'\]/);assert.match(migration,/Only draft or correction-required vacancies can be submitted/)});
test('profile protects legal and account fields',()=>['agency_name','main_email','gstin','verification_status','account_status'].forEach(k=>assert.match(pages[5],new RegExp(`name="${k}" disabled`))));
test('profile mutation is allowlisted and confirmed',()=>{assert.match(js,/update_contractor_portal_profile/);assert.match(js,/if\(ok!==true\)/)});
test('candidate projection is contact safe',()=>{assert.match(pages[2],/Contact details and internal notes are never shared/);assert.doesNotMatch(js,/candidate\.(mobile|whatsapp|internal_notes)/)});
test('application progress is read only',()=>{assert.match(js,/list_contractor_portal_applications/);assert.doesNotMatch(js,/transition_recruitment_application/)});
test('interview workspace is read only',()=>{assert.match(pages[3],/read-only/);assert.doesNotMatch(js,/schedule_recruitment_interview|update_recruitment_interview|reschedule_recruitment_interview/)});
test('joining workspace is read only',()=>{assert.match(pages[4],/read-only/);assert.doesNotMatch(js,/upsert_recruitment_joining/)});
test('no prompt alert UUID or raw status entry',()=>{assert.doesNotMatch(js,/\b(prompt|alert)\s*\(/);pages.forEach(s=>assert.doesNotMatch(s,/UUID|name=".*status.*" type="text"/))});
test('safe empty states and fallbacks exist',()=>{assert.match(js,/Not available/);assert.match(pages[1],/No vacancies found/);assert.match(pages[2],/No applications are available/)});
test('responsive tablet and mobile rules exist',()=>{assert.match(css,/@media\(max-width:900px\)/);assert.match(css,/@media\(max-width:760px\)/);assert.match(css,/@media\(max-width:600px\)/)});
test('tenant and approval security are server side',()=>{assert.match(migration,/current_contractor_portal_id/);assert.match(migration,/review_contractor_vacancy/);assert.match(migration,/requirement_stage='open'/)});
test('company ownership cannot be supplied by browser',()=>{assert.doesNotMatch(js,/company_id/);assert.match(migration,/origin_type='contractor_submission'/)});
test('internal W3 workspace exposes the approved review bridge',()=>{assert.match(admin,/Review Contractor Vacancies/);assert.match(admin,/list_contractor_vacancy_reviews/);assert.match(admin,/review_contractor_vacancy/)});
test('internal review actions follow the exact contractor vacancy state graph',()=>{assert.match(admin,/contractorReviewActions/);assert.match(admin,/approved:\[\['close','Close Vacancy'\]\]/);assert.doesNotMatch(admin,/approved:\[.*approve/)});
test('legacy assigned-requirements workflow remains available without mojibake',()=>{assert.match(pages[6],/Assigned Requirements/);assert.match(js,/get_staffing_partner_assignments/);assert.doesNotMatch(pages[6],/â|Ã/)});
