const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
class Element {
 constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.events={};this.attributes={};this.disabled=false;this.checked=false;this.isConnected=true;this._text='';}
 set textContent(v){this._text=String(v);this.children=[];} get textContent(){return this._text+this.children.map(c=>typeof c==='string'?c:c.textContent).join('');}
 append(...items){this.children.push(...items);}replaceChildren(...items){const disconnect=n=>{if(typeof n!=='string'){n.isConnected=false;n.children.forEach(disconnect);}};this.children.forEach(disconnect);this._text='';this.children=items;}
 setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,f){(this.events[k]??=[]).push(f);}async fire(k){for(const f of this.events[k]||[])await f({target:this});}
}
const all=(n,p)=>[...(p(n)?[n]:[]),...n.children.filter(c=>typeof c!=='string').flatMap(c=>all(c,p))];
function setup(handler){const popups=[],calls=[],timers=[],revoked=[];const win={addEventListener(){},open(){const p={opener:'parent',location:{replace(u){p.url=u;}},close(){p.closed=true;}};popups.push(p);return p;}};
 const sandbox={window:win,document:{createElement:t=>new Element(t),createTextNode:t=>String(t)},URL:{createObjectURL:()=> 'blob:local-test',revokeObjectURL:u=>revoked.push(u)},Blob,setTimeout:f=>timers.push(f)};vm.runInNewContext(fs.readFileSync('assets/js/resume-sharing.js','utf8'),sandbox);
 const client={rpc:async(name,args)=>{calls.push({name,args});return handler(name,args);},storage:{from(bucket){return{download:async name=>({data:new Blob(['%PDF-test']),error:null})}}}};
 return{api:win.AadhyantResumeSharing,client,root:new Element('section'),calls,popups,win,revoked,timers};}
const base={application_id:'app',recipients:[{recipient_type:'company',recipient_id:'co',recipient_name:'Company A',document_id:'doc',file_name:'resume.pdf',verified:true,consent_id:'consent',revision:'rev',consented:false,shared:false,has_grant:false}]};
const clone=o=>JSON.parse(JSON.stringify(o));
test('Candidate explicit consent starts unchecked and does not share automatically',async()=>{const state=clone(base);const x=setup(async name=>name==='get_candidate_resume_sharing'?{data:state}:{data:true});await x.api.candidate(x.root,x.client,'REQ');assert.equal(x.calls.length,1);const checkbox=all(x.root,n=>n.tagName==='INPUT')[0];const button=all(x.root,n=>n.tagName==='BUTTON')[0];assert.equal(checkbox.checked,false);assert.equal(button.disabled,true);await button.fire('click');assert.equal(x.calls.length,1);checkbox.checked=true;await checkbox.fire('change');assert.equal(button.disabled,false);await button.fire('click');assert.equal(x.calls[1].name,'set_candidate_resume_consent');assert.equal(x.calls[1].args.p_allow,true);assert.equal(x.calls.some(c=>c.name==='admin_set_application_resume_share'),false);assert.match(x.root.textContent,/contact details/);});
test('Candidate can withdraw consent explicitly',async()=>{const state=clone(base);state.recipients[0].consented=true;const x=setup(async name=>({data:name==='get_candidate_resume_sharing'?state:true}));await x.api.candidate(x.root,x.client,'REQ');await all(x.root,n=>n.tagName==='BUTTON')[0].fire('click');assert.equal(x.calls[1].args.p_allow,false);});
test('Admin share control requires consent and verified resume',async()=>{for(const [consented,verified,expected] of [[false,true,0],[true,false,0],[true,true,1]]){const state=clone(base);Object.assign(state.recipients[0],{consented,verified});const x=setup(async()=>({data:state}));await x.api.admin(x.root,x.client,'app');assert.equal(all(x.root,n=>n.tagName==='BUTTON').length,expected);}});
test('Admin shares exact consent revision; double-click has one write',async()=>{const state=clone(base);state.recipients[0].consented=true;let finish;const x=setup(name=>name==='admin_list_application_resume_sharing'?{data:state}:new Promise(r=>{finish=r;}));await x.api.admin(x.root,x.client,'app');const b=all(x.root,n=>n.tagName==='BUTTON')[0];const first=b.fire('click');await b.fire('click');assert.equal(x.calls.filter(c=>c.name==='admin_set_application_resume_share').length,1);assert.equal(x.calls[1].args.p_revision,'rev');finish({data:true});await first;});
test('Admin revoke remains available for an existing grant',async()=>{const state=clone(base);state.recipients[0].has_grant=true;const x=setup(async name=>({data:name==='admin_list_application_resume_sharing'?state:true}));await x.api.admin(x.root,x.client,'app');const b=all(x.root,n=>n.tagName==='BUTTON')[0];assert.equal(b.textContent,'Stop sharing');await b.fire('click');assert.equal(x.calls[1].args.p_share,false);});
test('Failed write preserves failure state and permits deliberate retry',async()=>{const state=clone(base);state.recipients[0].consented=true;const x=setup(async name=>name==='admin_list_application_resume_sharing'?{data:state}:{error:Error('private secret failure')});await x.api.admin(x.root,x.client,'app');const b=all(x.root,n=>n.tagName==='BUTTON')[0];await b.fire('click');assert.equal(b.disabled,false);assert.match(x.root.textContent,/could not be saved/);assert.doesNotMatch(x.root.textContent,/private secret/);});
test('Tenant has no button for an unavailable resume and rechecks access before download',async()=>{const empty=setup(async()=>({data:[]}));await empty.api.tenant(empty.root,empty.client,'app','company');assert.equal(all(empty.root,n=>n.tagName==='BUTTON').length,0);const x=setup(async name=>({data:name==='get_shared_application_resume'?[{document_id:'doc',display_file_name:'resume.pdf'}]:[{bucket_name:'candidate-private',object_name:'private/path.pdf'}]}));await x.api.tenant(x.root,x.client,'app','company');assert.equal(x.calls.length,1);await all(x.root,n=>n.tagName==='BUTTON')[0].fire('click');assert.equal(x.calls[1].name,'get_shared_application_resume_access');assert.equal(x.popups[0].opener,null);assert.equal(x.popups[0].url,'blob:local-test');assert.doesNotMatch(x.root.textContent,/private\/path/);});
test('Tenant stale access does not open a document or expose errors',async()=>{const x=setup(async name=>({data:name==='get_shared_application_resume'?[{document_id:'doc',display_file_name:'resume.pdf'}]:[]}));await x.api.tenant(x.root,x.client,'app','contractor');await all(x.root,n=>n.tagName==='BUTTON')[0].fire('click');assert.equal(x.popups[0].closed,true);assert.equal(x.popups[0].url,undefined);assert.match(x.root.textContent,/no longer available/);});
test('Disconnected modal receives no delayed sensitive content',async()=>{let release;const x=setup(()=>new Promise(r=>{release=r;}));const pending=x.api.tenant(x.root,x.client,'app','company');x.root.isConnected=false;release({data:[{document_id:'doc',display_file_name:'sensitive.pdf'}]});await pending;assert.doesNotMatch(x.root.textContent,/sensitive/);});
test('Shared module is explicitly included in each required portal and artifact allowlist',()=>{for(const f of ['candidate/portal/applications.html','admin/index.html','company/applications.html','contractor/applications.html'])assert.match(fs.readFileSync(f,'utf8'),/assets\/js\/resume-sharing\.js/);assert.match(fs.readFileSync('scripts/build-production-artifact.js','utf8'),/'assets\/js\/resume-sharing\.js'/);const s=fs.readFileSync('assets/js/resume-sharing.js','utf8');assert.doesNotMatch(s,/getPublicUrl|createSignedUrl|service_role|innerHTML|localStorage/);});

test('All four portal entry points invoke the correct sharing mode',()=>{for(const [file,mode] of [['candidate/portal/candidate.js','candidate'],['admin/recruitment-operations.js','admin'],['company/company.js','tenant'],['contractor/contractor.js','tenant']])assert.ok(fs.readFileSync(file,'utf8').includes('AadhyantResumeSharing?.'+mode+'('),file);});
