(function () {
  'use strict';
  if (document.body?.dataset.candidatePage !== 'jobs-batch2') return;
  const client=window.aadhyantSupabase?.client;const requested=String(new URLSearchParams(location.search).get('requirement')||'').trim().toUpperCase().match(/^[A-Z0-9_-]{1,64}$/)?.[0]||'';
  const call=async(name,args={})=>{const{data,error}=await client.rpc(name,args);if(error)throw error;return data;};const safe=(value)=>value===null||value===undefined||value===''?'—':String(value);const date=(value)=>value?new Date(value).toLocaleDateString('en-IN',{dateStyle:'medium'}):'—';
  async function start(){if(!client)return;const {data:sessionData}=await client.auth.getSession();if(!sessionData.session){location.replace('login.html');return;}try{await call('get_candidate_portal_context');}catch(_){location.replace('login.html');return;}document.querySelector('[data-loading]')?.setAttribute('hidden','');document.querySelector('[data-portal]')?.removeAttribute('hidden');document.querySelectorAll('[data-logout]').forEach((button)=>button.onclick=async()=>{await client.auth.signOut();location.replace('login.html');});const list=document.querySelector('[data-job-list]'),search=document.querySelector('[name=search]'),notice=document.querySelector('[data-message]');if(requested)search.value=requested;
    const message=(text,type='')=>{notice.textContent=text;notice.className=`message ${type}`;};const load=async()=>{const rows=await call('list_candidate_job_opportunities',{p_search:search.value.trim()||null,p_limit:50,p_offset:0})||[];list.replaceChildren();document.querySelector('[data-empty]').hidden=Boolean(rows.length);rows.forEach((row)=>{const card=document.createElement('article');card.className='job';const heading=document.createElement('div');heading.append(Object.assign(document.createElement('p'),{className:'eyebrow',textContent:row.requirement_code}),Object.assign(document.createElement('h2'),{textContent:safe(row.job_role)}),Object.assign(document.createElement('p'),{textContent:`${safe(row.job_location)} · ${row.open_positions} openings`}));card.append(heading);const detail=document.createElement('dl');detail.className='grid';[['Company / worksite',row.company_name||row.job_location],['Minimum CTC',row.salary_min],['Maximum CTC',row.salary_max],['Qualification',row.qualification],['Trade / specialization',row.iti_trade],['Experience',row.experience_requirement],['Shift',row.shift_details],['Facilities',[row.canteen,row.transport,row.accommodation].filter(Boolean).join(' · ')],['Interview location',row.interview_location],['Expected joining',date(row.expected_joining_date)],['Description',row.safe_description]].forEach(([label,value])=>{if(value===null||value===undefined||value==='')return;const item=document.createElement('div'),term=document.createElement('dt'),description=document.createElement('dd');term.textContent=label;description.textContent=safe(value);item.append(term,description);detail.append(item);});card.append(detail);const apply=document.createElement('button');apply.className='button';apply.type='button';apply.textContent=row.already_applied?'Applied':'Apply';apply.disabled=Boolean(row.already_applied);apply.onclick=async()=>{apply.disabled=true;try{await call('apply_candidate_job',{p_requirement_code:row.requirement_code});apply.textContent='Applied';message('Application submitted to Aadhyant.','success');}catch(_){apply.disabled=false;message('Your application could not be submitted. Please refresh and try again.','error');}};card.append(apply);list.append(card);});};document.querySelector('[data-search]').onsubmit=(event)=>{event.preventDefault();load().catch(()=>message('Opportunities could not be loaded.','error'));};await load();}
  start().catch(()=>{const node=document.querySelector('[data-message]');if(node)node.textContent='Opportunities are temporarily unavailable.';});
}());
