(() => {
  'use strict';

  const operationsDefinitions=Object.freeze([
    Object.freeze({key:'whatsappInbound',label:'Incoming / Replies',group:'whatsapp'}),
    Object.freeze({key:'whatsappAttention',label:'Failed / Attention',group:'whatsapp'})
  ]);
  const make=(tag,className='',text='')=>{const node=document.createElement(tag);if(className)node.className=className;if(text!=='')node.textContent=String(text);return node;};
  const call=async(client,name,args={})=>{const{data,error}=await client.rpc(name,args);if(error)throw error;return data;};
  const readable=(value)=>String(value??'—').replaceAll('_',' ').replace(/\b\w/g,(letter)=>letter.toUpperCase());
  const formatDateTime=(value)=>value?new Date(value).toLocaleString():'—';
  const safeFailure=(area)=>`${area} could not be loaded. Check the connection and retry.`;
  const attentionFrom=(failedOutbound=[],failedCampaigns=[],interviews=[],now=Date.now())=>({
    failedOutbound,
    failedCampaigns,
    overdueInterviews:(interviews||[]).filter((row)=>row.status==='scheduled'&&new Date(row.scheduled_at).getTime()<now)
  });
  let lastModule='recruitmentDashboard';

  const setSelected=(tab,panel,key)=>{document.querySelectorAll('[data-tab],[data-w3-tab],[data-product-tab]').forEach((item)=>item.setAttribute('aria-selected',String(item===tab)));document.querySelectorAll('[data-panel]').forEach((item)=>{item.hidden=item!==panel;});afterNavigation(key);};
  const statePanel=(text,kind='')=>make('div',`state-panel${kind?` state-panel-${kind}`:''}`,text);
  const tableFor=(columns,rows)=>{const wrap=make('div','table-wrap responsive-table');wrap.tabIndex=0;const table=make('table');const head=make('thead');const heading=make('tr');columns.forEach(([label])=>heading.append(make('th','',label)));head.append(heading);const body=make('tbody');rows.forEach((record)=>{const row=make('tr');columns.forEach(([label,value])=>{const cell=make('td','',value(record));cell.dataset.label=label;row.append(cell);});body.append(row);});table.append(head,body);wrap.append(table);return wrap;};

  const createInboundController=(client,panel)=>{
    let offset=0;let loading=false;const message=panel.querySelector('[data-product-message]');const workspace=panel.querySelector('[data-product-workspace]');
    const render=async()=>{if(loading)return;loading=true;workspace.replaceChildren(statePanel('Loading safe inbound metadata…','loading'));message.textContent='';message.classList.remove('is-error');try{const rows=await call(client,'list_whatsapp_recent_inbound',{p_limit:25,p_offset:offset});workspace.replaceChildren();const toolbar=make('div','section-heading');const title=make('div');title.append(make('h3','','Recent inbound replies'),make('p','bounded-note','Arbitrary free text and raw webhook payloads are intentionally excluded.'));const filter=make('select');filter.setAttribute('aria-label','Inbound processing status');['','accepted','processed','failed','ignored'].forEach((status)=>{const option=make('option','',status?readable(status):'All processing states');option.value=status;filter.append(option);});toolbar.append(title,filter);workspace.append(toolbar);const host=make('div');const renderRows=()=>{host.replaceChildren();const visible=rows.filter((row)=>!filter.value||row.processing_status===filter.value);if(!visible.length){host.append(statePanel(rows.length?'No replies match this processing state.':'No inbound replies are available.'));return;}host.append(tableFor([['Masked contact',(row)=>row.contact_masked||'—'],['Received',(row)=>formatDateTime(row.provider_timestamp)],['Message type',(row)=>readable(row.message_type)],['Structured action',(row)=>readable(row.action_id||'none')],['Processing',(row)=>readable(row.processing_status)]],visible));};filter.addEventListener('change',renderRows);renderRows();workspace.append(host);const pager=make('nav','pagination');pager.setAttribute('aria-label','Inbound reply pages');const previous=make('button','admin-button admin-button-quiet','Previous');previous.type='button';previous.disabled=offset===0;const label=make('span','',`Page ${Math.floor(offset/25)+1}`);const next=make('button','admin-button admin-button-quiet','Next');next.type='button';next.disabled=rows.length<25;previous.addEventListener('click',()=>{if(offset>=25){offset-=25;render();}});next.addEventListener('click',()=>{offset+=25;render();});pager.append(previous,label,next);workspace.append(pager);}catch(_error){workspace.replaceChildren();const error=statePanel(safeFailure('Inbound replies'),'error');const retry=make('button','admin-button admin-button-secondary','Retry');retry.type='button';retry.addEventListener('click',render);error.append(document.createTextNode(' '),retry);workspace.append(error);message.textContent='No sensitive error detail is displayed.';message.classList.add('is-error');}finally{loading=false;}};
    return{render};
  };

  const createAttentionController=(client,panel)=>{
    let loading=false;const message=panel.querySelector('[data-product-message]');const workspace=panel.querySelector('[data-product-workspace]');
    const section=(title,count,content)=>{const host=make('section','attention-section');const heading=make('div','section-heading');heading.append(make('h3','',title),make('span','attention-count',count));host.append(heading,content);return host;};
    const render=async()=>{if(loading)return;loading=true;workspace.replaceChildren(statePanel('Checking bounded attention queues…','loading'));message.textContent='';message.classList.remove('is-error');const results=await Promise.allSettled([call(client,'list_whatsapp_failed_outbound',{p_limit:50,p_offset:0}),call(client,'admin_list_whatsapp_campaigns',{p_status:'failed',p_limit:50,p_offset:0}),call(client,'list_recruitment_interviews',{p_upcoming_only:false,p_limit:100})]);try{const values=results.map((result)=>result.status==='fulfilled'?result.value:[]);const attention=attentionFrom(...values);workspace.replaceChildren();const note=make('p','bounded-note','Attention items are derived from existing bounded safe projections. No message retry or lifecycle mutation occurs here.');workspace.append(note);workspace.append(section('Failed outbound',attention.failedOutbound.length,attention.failedOutbound.length?tableFor([['Masked contact',(row)=>row.contact_masked],['Purpose',(row)=>readable(row.purpose)],['Failure category',(row)=>readable(row.error_category)],['Code',(row)=>row.error_code||'—'],['Attempts',(row)=>String(row.attempt_count??0)],['Failed',(row)=>formatDateTime(row.failed_at)]],attention.failedOutbound):statePanel('No failed outbound items.')));workspace.append(section('Failed campaigns',attention.failedCampaigns.length,attention.failedCampaigns.length?tableFor([['Campaign',(row)=>row.campaign_name],['Vacancy',(row)=>`${row.requirement_code} · ${row.job_role}`],['Audience',(row)=>String(row.audience_count??0)],['Failed',(row)=>String(row.failed_count??0)],['Created',(row)=>formatDateTime(row.created_at)]],attention.failedCampaigns):statePanel('No failed campaigns.')));workspace.append(section('Interview attention',attention.overdueInterviews.length,attention.overdueInterviews.length?tableFor([['Candidate',(row)=>row.candidate_name],['Requirement',(row)=>row.requirement_code],['Scheduled',(row)=>formatDateTime(row.scheduled_at)],['Mode',(row)=>readable(row.mode)],['Status',(row)=>readable(row.status)]],attention.overdueInterviews):statePanel('No overdue scheduled interviews in the latest bounded projection.')));const refresh=make('button','admin-button admin-button-secondary','Refresh Attention');refresh.type='button';refresh.addEventListener('click',render);workspace.append(refresh);if(results.some((result)=>result.status==='rejected')){message.textContent='Some attention sources are temporarily unavailable.';message.classList.add('is-error');}}finally{loading=false;}};
    return{render};
  };

  const afterNavigation=(key)=>{lastModule=key||lastModule;const sidebar=document.querySelector('[data-admin-sidebar]');const toggle=document.querySelector('[data-nav-toggle]');sidebar?.classList.remove('is-open');if(toggle)toggle.setAttribute('aria-expanded','false');const selected=document.querySelector('[aria-selected="true"]');if(selected)document.title=`${selected.textContent.trim()} | Aadhyant Admin`;window.history?.replaceState?.(null,'',`#${lastModule}`);document.querySelector('#admin-workspace')?.focus({preventScroll:true});};

  const initialize=async({client,authorization})=>{
    const tabs=document.querySelector('.admin-tabs');const main=document.querySelector('.admin-main');const group=document.querySelector('[data-nav-group="whatsapp"]');if(!tabs||!main||!group)return false;
    const sessionCard=document.querySelector('.admin-session-card');if(sessionCard){sessionCard.hidden=false;const name=sessionCard.querySelector('[data-staff-session-name]');const roles=sessionCard.querySelector('[data-staff-session-roles]');name.textContent=authorization?.display_name||'Aadhyant staff';roles.textContent=(authorization?.roles||[]).map(readable).join(', ')||(authorization?.bootstrap_admin?'Bootstrap Admin':'Authorized access');}
    const canViewWhatsApp=Boolean(authorization?.bootstrap_admin||authorization?.staff_management_access);const controllers=new Map();
    if(canViewWhatsApp)operationsDefinitions.forEach((definition)=>{const tab=make('button','',definition.label);tab.type='button';tab.dataset.productTab=definition.key;tab.setAttribute('aria-selected','false');const panel=make('section','record-panel product-panel');panel.dataset.panel=definition.key;panel.hidden=true;const heading=make('div','panel-heading');const copy=make('div');copy.append(make('p','admin-eyebrow','Safe operations projection'),make('h2','',definition.label),make('p','',definition.key==='whatsappInbound'?'Masked structured inbound metadata from W7A.':'Failed communication and overdue interview items requiring review.'));heading.append(copy);const message=make('div','admin-message');message.dataset.productMessage='';message.setAttribute('role','status');message.setAttribute('aria-live','polite');const workspace=make('div','product-workspace');workspace.dataset.productWorkspace='';panel.append(heading,message,workspace);group.append(tab);main.insertBefore(panel,document.querySelector('[data-panel="staff"]'));const controller=definition.key==='whatsappInbound'?createInboundController(client,panel):createAttentionController(client,panel);controllers.set(definition.key,controller);tab.addEventListener('click',()=>{setSelected(tab,panel,definition.key);controller.render();});});
    const toggle=document.querySelector('[data-nav-toggle]');const sidebar=document.querySelector('[data-admin-sidebar]');toggle?.addEventListener('click',()=>{const open=!sidebar.classList.contains('is-open');sidebar.classList.toggle('is-open',open);toggle.setAttribute('aria-expanded',String(open));});
    document.addEventListener('click',(event)=>{const action=event.target.closest?.('[data-open-module]');if(!action)return;const target=document.querySelector(`[data-w3-tab="${action.dataset.openModule}"],[data-product-tab="${action.dataset.openModule}"]`);target?.click();if(action.dataset.openModule==='whatsappCampaigns')setTimeout(()=>document.querySelector('[data-panel="whatsappCampaigns"] .panel-heading .admin-button-primary')?.focus(),0);});
    const requested=window.location?.hash?.slice(1)||'';const initial=document.querySelector(`[data-w3-tab="${requested}"],[data-product-tab="${requested}"],[data-tab="${requested}"]:not([hidden])`)||document.querySelector('[data-w3-tab="recruitmentDashboard"]')||document.querySelector('[data-tab="staff"]:not([hidden])');initial?.click();return true;
  };

  window.aadhyantAdminProduct=Object.freeze({initialize,afterNavigation,operationsDefinitions,attentionFrom,safeFailure,get lastModule(){return lastModule;}});
})();
