(function () {
  'use strict';
  const text = (value) => value === null || value === undefined || value === '' ? '—' : String(value);
  const readable = (value) => text(value).replaceAll('_',' ').replace(/\b\w/g,(letter) => letter.toUpperCase());
  const date = (value) => value ? new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}) : '—';
  const call = async (client,name,args={}) => { const {data,error}=await client.rpc(name,args);if(error)throw error;return data; };
  const make = (tag,className='',value='') => { const node=document.createElement(tag);if(className)node.className=className;if(value !== '')node.textContent=value;return node; };
  const vacancyStatus = (detail) => { const review=detail?.review?.normalized_status;if(review==='approved'&&detail?.lifecycle?.requirement_stage==='open'&&detail?.lifecycle?.requirement_visibility==='public')return 'Published / Open';return ({draft:'Draft',pending_review:'Pending Review',correction_required:'Correction Required',rejected:'Rejected',closed:'Closed'}[review] || readable(review)); };
  const section = (title, pairs) => { const block=make('section','vacancy-review-section');block.append(make('h3','',title));const list=make('dl','detail-list');pairs.forEach(([label,value])=>{const item=make('div');item.append(make('dt','',label),make('dd','',text(value)));list.append(item);});block.append(list);return block; };
  const compensationSection = (vacancy) => {
    const compensation=window.AadhyantVacancyCompensation;
    if(!compensation?.hasStructuredSalary(vacancy))return section('Salary / Wage Details',[['Legacy minimum CTC',vacancy.salary_min],['Legacy maximum CTC',vacancy.salary_max]]);
    const money=(value)=>compensation.money(value);
    return section('Salary / Wage Details',[['Payable Days',vacancy.payable_days],['Basic + DA',money(vacancy.basic_da)],['Attendance Bonus',money(vacancy.attendance_bonus)],['Monthly Bonus',money(vacancy.monthly_bonus)],['EL / Leave Amount',money(vacancy.leave_amount)],['Other Fixed Earning',money(vacancy.other_fixed_earning)],['Gross Wages',money(vacancy.gross_wages)],['Employee PF',money(vacancy.employee_pf)],['Employee ESIC',money(vacancy.employee_esic)],['Canteen Deduction',money(vacancy.canteen_deduction)],['Other Deduction',money(vacancy.other_deduction)],['Employer PF',money(vacancy.employer_pf)],['Employer ESIC',money(vacancy.employer_esic)],['Gratuity Provision',money(vacancy.gratuity_provision)],['Bonus Provision',money(vacancy.bonus_provision)],['Leave Provision',money(vacancy.leave_provision)],['Other CTC Component',money(vacancy.other_ctc_component)],['Approx. In-Hand',money(vacancy.approx_in_hand)],['CTC',money(vacancy.ctc)]]);
  };
  async function openDetail(client, requirementId, reload) {
    const detail=await call(client,'admin_get_vacancy_review_detail',{p_requirement_id:requirementId});const rawVacancy=detail?.vacancy||{},displayHelper=window.AadhyantVacancyCompensation;const vacancy={...rawVacancy,...(rawVacancy.compensation||{}),accommodation_detail:rawVacancy.accommodation_detail||{}};vacancy.canteen=displayHelper?.facility(rawVacancy.canteen)||rawVacancy.canteen;vacancy.transport=displayHelper?.facility(rawVacancy.transport)||rawVacancy.transport;vacancy.accommodation=displayHelper?.accommodation(vacancy)||rawVacancy.accommodation;const source=detail?.source||{},review=detail?.review||{},lifecycle=detail?.lifecycle||{},progress=detail?.progress||{};
    const dialog=make('dialog','detail-dialog unified-vacancy-review-dialog');dialog.setAttribute('aria-labelledby','unified-vacancy-title');const heading=make('div','dialog-heading');const copy=make('div');copy.append(make('p','admin-eyebrow','Unified vacancy review'),make('h2','',`${vacancy.requirement_code||'Vacancy'} · ${text(vacancy.job_role)}`));copy.querySelector('h2').id='unified-vacancy-title';const close=make('button','dialog-close','×');close.type='button';close.setAttribute('aria-label','Close vacancy review');heading.append(copy,close);
    const feedback=make('p','status-warning',review.feedback ? `Feedback: ${review.feedback}` : 'No review feedback has been recorded.');
    const reasonField=make('div','admin-field');const reason=make('textarea');reason.name='reviewReason';reason.maxLength=2000;reason.rows=3;reason.placeholder='Required for correction or rejection';reasonField.append(make('label','','Correction or rejection reason'),reason);
    const actions=make('div','dialog-actions');const message=make('div','admin-message');message.setAttribute('role','status');message.setAttribute('aria-live','polite');
    const pending=review.normalized_status==='pending_review';const run=async(action)=>{if(['correction','reject'].includes(action)&&!reason.value.trim()){message.textContent='Enter a clear candidate-facing reason before continuing.';message.classList.add('is-error');return;}actions.querySelectorAll('button').forEach((button)=>button.disabled=true);try{if(action==='approve')await call(client,'admin_approve_and_publish_vacancy',{p_requirement_id:requirementId});if(action==='correction')await call(client,'admin_request_vacancy_correction',{p_requirement_id:requirementId,p_reason:reason.value.trim()});if(action==='reject')await call(client,'admin_reject_vacancy',{p_requirement_id:requirementId,p_reason:reason.value.trim()});dialog.close();dialog.remove();await reload();}catch(_){message.textContent='The review action could not be completed. Refresh and try again.';message.classList.add('is-error');actions.querySelectorAll('button').forEach((button)=>button.disabled=false);}};
    if(pending){[['Approve & Publish','approve','admin-button admin-button-primary'],['Request Correction','correction','admin-button admin-button-secondary'],['Reject','reject','admin-button admin-button-quiet']].forEach(([label,action,className])=>{const button=make('button',className,label);button.type='button';button.onclick=()=>run(action);actions.append(button);});}
    const done=make('button','admin-button admin-button-quiet','Close');done.type='button';done.onclick=()=>{dialog.close();dialog.remove();};actions.append(done);
    dialog.append(heading,
      section('Source',[['Source type',readable(source.source_type)],['Submitted by',source.submitted_by],['Company',source.company],['Contractor',source.contractor]]),
      section('Full Vacancy Details',[['Requirement code',vacancy.requirement_code],['Job role',vacancy.job_role],['Department',vacancy.department],['Location',vacancy.location],['Openings',vacancy.openings],['Qualification',vacancy.qualification],['Trade / specialization',vacancy.iti_trade],['Experience',vacancy.experience_requirement],['Gender',vacancy.gender_preference],['Age range',[vacancy.age_min,vacancy.age_max].filter((value)=>value!==null&&value!==undefined).join(' – ')],['Minimum CTC',vacancy.salary_min],['Maximum CTC',vacancy.salary_max],['Shift',vacancy.shift_details],['Duty hours',vacancy.working_hours],['Overtime details',vacancy.overtime_details],['Canteen',vacancy.canteen],['Transport',vacancy.transport],['Accommodation',vacancy.accommodation],['Interview location',vacancy.interview_location],['Expected joining',vacancy.expected_joining_date],['Description / remarks',vacancy.additional_notes]]),
      compensationSection(vacancy),
      section('Review / Lifecycle',[['Status',vacancyStatus(detail)],['Requirement stage',readable(lifecycle.requirement_stage)],['Visibility',readable(lifecycle.requirement_visibility)],['Submitted',date(review.submitted_at)],['Reviewed',date(review.reviewed_at)],['Feedback',review.feedback]]),
      section('Recruitment Progress',[['Applications',progress.applications||0],['Screening','—'],['Shortlisted','—'],['Interviews',progress.interviews||0],['Selected',progress.selected||0],['Joined',progress.joined||0],['Filled',lifecycle.filled_positions||0],['Remaining',lifecycle.remaining_positions||0]]),
      pending ? reasonField : make('p','stage-terminal-message','This vacancy has no pending review action.'),actions,message);
    document.body.append(dialog);dialog.addEventListener('cancel',(event)=>{event.preventDefault();done.click();});dialog.showModal();close.focus();
  }
  async function initialize({client,authorization}){
    if(!client||!(authorization?.bootstrap_admin||authorization?.staff_management_access))return false;
    const group=document.querySelector('[data-nav-group="recruitment"]'),main=document.querySelector('.admin-main');if(!group||!main||document.querySelector('[data-batch2-vacancy-review]'))return true;
    const tab=make('button','', 'Vacancy Reviews');tab.type='button';tab.dataset.batch2VacancyReview='';tab.setAttribute('aria-selected','false');group.append(tab);
    const panel=make('section','record-panel w3-panel');panel.dataset.panel='batch2VacancyReview';panel.hidden=true;panel.dataset.batch2VacancyReview='';const heading=make('div','panel-heading');const copy=make('div');copy.append(make('p','admin-eyebrow','Company and Contractor submissions'),make('h2','','Vacancy Reviews'),make('p','','Review the complete, canonical vacancy before approving, requesting correction, or rejecting it.'));heading.append(copy);const state=make('div','admin-message');state.setAttribute('role','status');state.setAttribute('aria-live','polite');const filters=make('form','filter-grid');const status=make('select');status.name='status';['','pending_review','correction_required','approved','rejected','closed'].forEach((value)=>{const option=make('option','',value?readable(value):'All statuses');option.value=value;status.append(option);});const field=make('div','admin-field');field.append(make('label','','Review status'),status);const submit=make('button','admin-button admin-button-primary','Apply Filter');submit.type='submit';filters.append(field,submit);const wrap=make('div','table-wrap responsive-table');const table=make('table');const head=make('thead'),headRow=make('tr');['Code / Role','Source','Company / Contractor','Openings','Status','Submitted','Action'].forEach((label)=>headRow.append(make('th','',label)));head.append(headRow);const body=make('tbody');table.append(head,body);wrap.append(table);panel.append(heading,state,filters,wrap);main.insertBefore(panel,document.querySelector('[data-panel="staff"]'));
    const load=async()=>{body.replaceChildren();state.textContent='Loading vacancy reviews…';try{const rows=await call(client,'admin_list_vacancy_reviews',{p_review_status:status.value||null,p_source_type:null,p_limit:100,p_offset:0})||[];rows.forEach((row)=>{const tr=make('tr');[[`${row.requirement_code} · ${row.job_role}`,'Code / Role'],[readable(row.source_type),'Source'],[[row.company_name,row.contractor_name].filter(Boolean).join(' · '),'Company / Contractor'],[row.remaining_positions ?? row.required_headcount,'Openings'],[readable(row.normalized_review_status),'Status'],[date(row.submitted_at),'Submitted']].forEach(([value,label])=>{const cell=make('td','',text(value));cell.dataset.label=label;tr.append(cell);});const action=make('td','table-actions');action.dataset.label='Action';const view=make('button','table-action table-action-primary','View & Review');view.type='button';view.onclick=()=>openDetail(client,row.requirement_id,load).catch(()=>{state.textContent='Vacancy detail could not be loaded.';});action.append(view);tr.append(action);body.append(tr);});state.textContent=rows.length?'':'No vacancy reviews match this filter.';}catch(_){state.textContent='Vacancy reviews could not be loaded. Retry from the filter.';state.classList.add('is-error');}};
    filters.onsubmit=(event)=>{event.preventDefault();load();};tab.onclick=async()=>{document.querySelectorAll('[data-tab],[data-w3-tab],[data-product-tab],[data-batch2-vacancy-review]').forEach((button)=>button.setAttribute('aria-selected',String(button===tab)));document.querySelectorAll('[data-panel]').forEach((node)=>node.hidden=node!==panel);await load();};
    return true;
  }
  window.aadhyantVacancyReview=Object.freeze({initialize,vacancyStatus});
}());
