import {classifyRequest,observePdfBlobs,verifyBrowserDownload} from './browser_download_evidence.mjs';
import {chromium,expect} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const e=process.env,front=new URL(e.RESUME_E2E_URL||''),back=new URL(e.RESUME_E2E_BACKEND||''),key=e.RESUME_E2E_ANON_KEY;
for(const u of [front,back])if(u.protocol!=='http:'||u.hostname!=='127.0.0.1'||!u.port||u.pathname!=='/'||u.username||u.password||u.hash||u.search)throw Error('LOOPBACK_ONLY');
if(!key||!e.RESUME_E2E_PASSWORD||!e.RESUME_E2E_SITE||!e.RESUME_E2E_EVIDENCE_DIR)throw Error('EXPLICIT_LOCAL_INPUTS_REQUIRED');
if(!key.startsWith('sb_publishable_')&&JSON.parse(Buffer.from(key.split('.')[1],'base64url')).role!=='anon')throw Error('NO_PRIVILEGED_BROWSER_KEY');
const module=await readFile(join(e.RESUME_E2E_SITE,'assets/js/resume-sharing.js'));
const actors=JSON.parse(await readFile(join(e.RESUME_E2E_EVIDENCE_DIR,'synthetic-actors.json'),'utf8'));
const state=JSON.parse(await readFile(join(e.RESUME_E2E_EVIDENCE_DIR,'fixture-state.json'),'utf8'));
const sdk='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.4';
const results={scope:'Actual new resume-sharing browser component with genuine local Auth/Storage and SQL APIs. This does not exercise every surrounding portal page.',checks:{},nonlocalBackendRequests:0,blockedRequests:[],internalPdfViewerRequests:0,internalChromeResourceRequests:0,downloads:{}};let browser,server,stage='START';
const pass=n=>{results.checks[n]='PASS';console.log(n+'=PASS');};
const html=`<!doctype html><html><head><meta charset="utf-8"><title>Local resume sharing rehearsal</title></head><body><form id="login"><label>Email<input name="email" type="email"></label><label>Password<input name="password" type="password"></label><button>Sign in</button></form><main id="sharing"></main><script src="${sdk}" integrity="sha384-yiVMs0R/Jyz7OhoXa/DsEMUSBLjEhr/QJta2ONO+zB6I8/GmNg/7AUFrZmAJV7KV" crossorigin="anonymous"></script><script src="/resume-sharing.js"></script><script>
window.client=supabase.createClient(${JSON.stringify(back.origin)},${JSON.stringify(key)},{auth:{persistSession:false,autoRefreshToken:false}});
document.querySelector('#login').onsubmit=async event=>{event.preventDefault();const f=event.target;const {error}=await client.auth.signInWithPassword({email:f.elements.email.value,password:f.elements.password.value});if(error)throw Error('LOCAL_LOGIN_FAILED');f.hidden=true;window.localAuthenticated=true;};
</script></body></html>`;
try{
 server=createServer((req,res)=>{if(req.method!=='GET'){res.writeHead(405);res.end();return;}if(req.url==='/resume-sharing.js'){res.writeHead(200,{'Content-Type':'text/javascript'});res.end(module);}else if(req.url==='/'){res.writeHead(200,{'Content-Type':'text/html','Cache-Control':'no-store'});res.end(html);}else{res.writeHead(404);res.end();}});await new Promise(ok=>server.listen(Number(front.port),'127.0.0.1',ok));
 browser=await chromium.launch({channel:'chrome',headless:true});
 async function pageFor(name){const ctx=await browser.newContext({serviceWorkers:'block'});await ctx.addInitScript(observePdfBlobs);await ctx.route('**/*',route=>{const request=route.request(),u=new URL(request.url()),kind=classifyRequest(u.href,{frontend:front.origin,backend:back.origin,sdk},request.method(),request.resourceType());if(kind==='BUILTIN_PDF_VIEWER')results.internalPdfViewerRequests++;if(kind==='BUILTIN_CHROME_RESOURCE')results.internalChromeResourceRequests++;if(kind!=='BLOCKED')return route.continue();results.nonlocalBackendRequests++;results.blockedRequests.push({actor:name,scheme:u.protocol,origin:u.origin==='null'?u.protocol+'//'+u.hostname:u.origin,method:request.method(),resourceType:request.resourceType()});return route.abort();});const p=await ctx.newPage();p.setDefaultTimeout(30000);await p.goto(front.origin);await p.locator('[name=email]').fill(actors[name].email);await p.locator('[name=password]').fill(e.RESUME_E2E_PASSWORD);await p.getByRole('button',{name:'Sign in'}).click();await p.waitForFunction(()=>window.localAuthenticated===true);return p;}
 const a=await pageFor('candidate'),admin=await pageFor('admin'),company=await pageFor('company'),other=await pageFor('otherCompany'),contractor=await pageFor('contractor');pass('GENUINE_BROWSER_PASSWORD_LOGINS');
 const candidateView=(p,code)=>p.evaluate(code=>window.AadhyantResumeSharing.candidate(document.querySelector('#sharing'),window.client,code),code);
 const adminView=(id)=>admin.evaluate(id=>window.AadhyantResumeSharing.admin(document.querySelector('#sharing'),window.client,id),id);
 const tenantView=(p,id,role)=>p.evaluate(({id,role})=>window.AadhyantResumeSharing.tenant(document.querySelector('#sharing'),window.client,id,role),{id,role});
 stage='CANDIDATE_EXPLICIT_CONSENT';await candidateView(a,'E2E-SHARE-1');await expect(a.getByRole('checkbox')).not.toBeChecked();await expect(a.getByRole('button',{name:'Allow Admin to share'})).toBeDisabled();await a.getByRole('checkbox').check();await a.getByRole('button',{name:'Allow Admin to share'}).click();await expect(a.getByRole('button',{name:'Withdraw consent'})).toBeVisible();pass(stage);
 stage='CONSENT_WITHOUT_ADMIN_DENIED';await tenantView(company,state.app,'company');await expect(company.getByRole('button',{name:'View Resume'})).toHaveCount(0);pass(stage);
 stage='ADMIN_EXPLICIT_SHARE';await adminView(state.app);await admin.getByRole('button',{name:'Share Resume',exact:true}).click();await expect(admin.getByRole('button',{name:'Stop sharing'})).toBeVisible();pass(stage);
 stage='COMPANY_GENUINE_STORAGE_DOWNLOAD';await tenantView(company,state.app,'company');results.downloads.company={};await verifyBrowserDownload(company,state,back.origin,results.downloads.company);pass(stage);
 stage='OTHER_COMPANY_DENIED';await tenantView(other,state.app,'company');await expect(other.getByRole('button',{name:'View Resume'})).toHaveCount(0);const blocked=await other.evaluate(async path=>Boolean((await window.client.storage.from('candidate-private').download(path)).error),state.objectName);expect(blocked).toBe(true);pass(stage);
 stage='CANDIDATE_REVOCATION';await a.getByRole('button',{name:'Withdraw consent'}).click();await expect(a.getByRole('button',{name:'Allow Admin to share'})).toBeVisible();await tenantView(company,state.app,'company');await expect(company.getByRole('button',{name:'View Resume'})).toHaveCount(0);pass(stage);
 stage='CONTRACTOR_CONSENT_AND_ADMIN_SHARE';await candidateView(a,'E2E-SHARE-2');await a.getByRole('checkbox').check();await a.getByRole('button',{name:'Allow Admin to share'}).click();await expect(a.getByRole('button',{name:'Withdraw consent'})).toBeVisible();await adminView(state.contractorApp);await admin.getByRole('button',{name:'Share Resume',exact:true}).click();await expect(admin.getByRole('button',{name:'Stop sharing'})).toBeVisible();await tenantView(contractor,state.contractorApp,'contractor');await expect(contractor.getByRole('button',{name:'View Resume'})).toBeVisible();pass(stage);
 stage='CONTRACTOR_GENUINE_STORAGE_DOWNLOAD';results.downloads.contractor={};await verifyBrowserDownload(contractor,state,back.origin,results.downloads.contractor);pass(stage);
 stage='ADMIN_REVOCATION';await admin.getByRole('button',{name:'Stop sharing'}).click();await expect(admin.getByRole('button',{name:'Share Resume',exact:true})).toBeVisible();await tenantView(contractor,state.contractorApp,'contractor');await expect(contractor.getByRole('button',{name:'View Resume'})).toHaveCount(0);pass(stage);
 stage='BACKEND_LOOPBACK_GUARD';expect(results.nonlocalBackendRequests).toBe(0);pass(stage);results.result='PASS';console.log('RESUME_BROWSER_COMPONENT_FLOW=PASS');
}catch(err){results.result='FAIL';results.failureStage=stage;results.error=String(err.message).replaceAll(e.RESUME_E2E_PASSWORD||'','[REDACTED]').replaceAll(key,'[REDACTED]').replace(/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/g,'[REDACTED_JWT]').slice(0,1200);console.error(stage+'=FAIL');console.error('FAILURE_DETAIL='+results.error);if(Object.keys(results.downloads).length)console.error('DOWNLOAD_EVIDENCE='+JSON.stringify(results.downloads));if(results.blockedRequests.length)console.error('BLOCKED_REQUESTS='+JSON.stringify(results.blockedRequests));process.exitCode=1;}
finally{await browser?.close();if(server)await new Promise(ok=>server.close(ok));await writeFile(join(e.RESUME_E2E_EVIDENCE_DIR,'resume-browser-result.json'),JSON.stringify(results,null,2)+'\n');}
