BEGIN READ ONLY;
WITH wanted(identity) AS (VALUES
('public.admin_list_candidate_documents(uuid)'),('public.admin_get_candidate_document_access(uuid)'),('public.admin_review_candidate_document(uuid,text,text)'),
('private.can_verify_candidate_documents()'),('private.can_read_candidate_storage_object(text)'),('private.is_current_candidate_storage_path(text)'),('private.can_delete_candidate_storage_object(text)'),
('private.current_candidate_portal_id()'),('private.is_bootstrap_recruitment_admin()'),('private.is_admin()'),('private.has_staff_role(text)'),('private.current_staff_roles()'),('private.current_staff_profile_id()'),('private.set_updated_at()'),('auth.uid()'),('storage.foldername(text)'),('private.current_company_portal_id(boolean)'),('private.current_contractor_portal_id(boolean)')),
tables(identity) AS (VALUES ('auth.users'),('public.admin_users'),('public.platform_users'),('public.staff_profiles'),('public.staff_roles'),('public.candidates'),('public.candidate_documents'),('public.audit_logs'),('storage.buckets'),('storage.objects'),('public.companies'),('public.company_users'),('public.contractors'),('public.contractor_users'),('public.employer_requirements'),('public.requirement_contractors'),('public.candidate_applications'))
SELECT jsonb_build_object(
'functions',(SELECT jsonb_agg(jsonb_build_object('identity',w.identity,'oid',p.oid,'status',CASE WHEN p.oid IS NULL THEN 'ABSENT' ELSE 'PRESENT' END,'definition',pg_get_functiondef(p.oid),'owner',pg_get_userbyid(p.proowner),'proconfig',p.proconfig,'security_definer',p.prosecdef,'acl',p.proacl::text,'hash',md5(p.prosrc),'authenticated',CASE WHEN p.oid IS NOT NULL THEN has_function_privilege('authenticated',p.oid,'EXECUTE') END,'anon',CASE WHEN p.oid IS NOT NULL THEN has_function_privilege('anon',p.oid,'EXECUTE') END) ORDER BY w.identity) FROM wanted w LEFT JOIN pg_proc p ON p.oid=to_regprocedure(w.identity)),
'overloads',(SELECT coalesce(jsonb_agg(p.oid::regprocedure::text ORDER BY p.oid::regprocedure::text),'[]') FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('get_candidate_resume_sharing','set_candidate_resume_consent','admin_list_application_resume_sharing','admin_set_application_resume_share','get_shared_application_resume','get_shared_application_resume_access')),
'tables',(SELECT jsonb_agg(jsonb_build_object('identity',t.identity,'rls',c.relrowsecurity,'acl',c.relacl::text,
'columns',(SELECT jsonb_agg(jsonb_build_object('name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid)) ORDER BY a.attnum) FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped),
'constraints',(SELECT jsonb_agg(jsonb_build_object('name',conname,'type',contype,'definition',pg_get_constraintdef(oid),'validated',convalidated) ORDER BY conname) FROM pg_constraint WHERE conrelid=c.oid),
'indexes',(SELECT jsonb_agg(pg_get_indexdef(i.indexrelid) ORDER BY i.indexrelid::regclass::text) FROM pg_index i WHERE i.indrelid=c.oid AND NOT EXISTS(SELECT 1 FROM pg_constraint co WHERE co.conindid=i.indexrelid)),
'triggers',(SELECT jsonb_agg(jsonb_build_object('name',tgname,'enabled',tgenabled,'definition',pg_get_triggerdef(oid),'function_identity',tgfoid::regprocedure::text) ORDER BY tgname) FROM pg_trigger WHERE tgrelid=c.oid AND NOT tgisinternal)) ORDER BY t.identity) FROM tables t LEFT JOIN pg_class c ON c.oid=to_regclass(t.identity)),
'storage_policies',(SELECT jsonb_agg(jsonb_build_object('name',policyname,'roles',roles,'cmd',cmd,'qual',qual,'with_check',with_check) ORDER BY policyname) FROM pg_policies WHERE schemaname='storage' AND tablename='objects'),
'bucket',(SELECT jsonb_build_object('public',public,'file_size_limit',file_size_limit,'allowed_mime_types',allowed_mime_types) FROM storage.buckets WHERE id='candidate-private')) AS catalog;
ROLLBACK;
