// Local SQL engine + synthetic SQL principals. No genuine Auth JWT/Storage-service proof.
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createHash} from 'node:crypto';
const toolsRoot=process.env.RESUME_SQL_TOOLS;if(!toolsRoot)throw Error('RESUME_SQL_TOOLS required');
const {PGlite}=await import(pathToFileURL(join(toolsRoot,'protocol_tools/node_modules/@electric-sql/pglite/dist/index.js')));
const {PGLiteSocketServer}=await import(pathToFileURL(join(toolsRoot,'protocol_tools/node_modules/@electric-sql/pglite-socket/dist/index.js')));
const here=fileURLToPath(new URL('.',import.meta.url));const read=n=>readFile(join(here,n),'utf8');const exec=promisify(execFile);
const db=new PGlite(),server=new PGLiteSocketServer({db,host:'127.0.0.1',port:0,maxConnections:1});
const query=async(s,p=[])=>(await db.query(s,p)).rows,sql=s=>db.exec(s);
const proof={scope:'Native psql 17 -> local PostgreSQL17/PGlite. Exact captured SQL constraints/helpers; synthetic SQL principals. Not genuine Auth/Storage or full browser E2E.',checks:{}};
const pass=n=>{proof.checks[n]='PASS';console.log(n+'=PASS');};
const psql=join(toolsRoot,'psql17/files/usr/lib/postgresql/17/bin/psql'),lib=join(toolsRoot,'psql17/files/usr/lib/x86_64-linux-gnu');
async function run(file,marker,code=0){let r;try{r=await exec(psql,['-X','-A','-t','--no-password','-v','ON_ERROR_STOP=1','-f',join(here,file)],{env:{...process.env,LD_LIBRARY_PATH:lib,PGHOST:'127.0.0.1',PGPORT:server.getServerConn().split(':').at(-1),PGUSER:'postgres',PGDATABASE:'template1',PGSSLMODE:'disable',PGOPTIONS:'',PGPASSWORD:'local-only'},timeout:60000,maxBuffer:2*1024*1024});r.code=0;}catch(e){r=e;}
 assert.equal(r.code,code,(r.stderr||'')+'\n'+r.stdout);if(marker)assert.ok(r.stdout.split(/\r?\n/).includes(marker),r.stdout);return r;}
const uid=n=>'e0000000-0000-0000-0000-'+String(n).padStart(12,'0');
const user={admin:uid(1),a:uid(2),b:uid(3),coA:uid(4),coB:uid(5),coViewer:uid(6),ctA:uid(7),ctB:uid(8),ctViewer:uid(9),staff:uid(10)};
const co=uid(21),coB=uid(22),ct=uid(23),ctB=uid(24),cand=uid(31),candB=uid(32),doc=uid(41),pan=uid(42),replacement=uid(43),app=uid(61),ctApp=uid(62),otherApp=uid(63);
const req=uid(51),ctReq=uid(52),otherReq=uid(53),obj=uid(71);const objectName=user.a+'/'+doc+'/synthetic.pdf';
async function as(u='',role='authenticated'){await sql('RESET ROLE');await query("SELECT set_config('request.jwt.claim.sub',$1,false)",[u]);await sql('SET ROLE '+role);}
async function denied(s,p=[],code='P0001'){let e;try{await query(s,p);}catch(err){e=err;}assert.ok(e,'Expected failure '+s);assert.equal(e.code,code,e.message);}
const consent=(application=app,document=doc,type='company',recipient=co,allow=true)=>query('SELECT public.set_candidate_resume_consent($1,$2,$3,$4,$5)',[application,document,type,recipient,allow]);
const list=(application=app,portal='company')=>query('SELECT * FROM public.get_shared_application_resume($1,$2)',[application,portal]);
const storage=()=>query('SELECT name FROM storage.objects WHERE name=$1',[objectName]);
async function shareRecord(application=app,type='company'){const r=await query('SELECT public.admin_list_application_resume_sharing($1) data',[application]);return r[0].data.recipients.find(r=>r.recipient_type===type);}
const setShare=async(r,yes=true)=>{const result=await query('SELECT public.admin_set_application_resume_share($1,$2,$3)',[r.consent_id,r.revision,yes]);const data=await shareRecord(r.recipient_type==='contractor'?ctApp:app,r.recipient_type);Object.assign(r,data);return result;};
const review=status=>query('SELECT public.admin_review_candidate_document($1,$2,NULL)',[doc,status]);
try{
 const m=JSON.parse(await read('manifest.json'));for(const [f,h] of Object.entries(m.files))assert.equal(createHash('sha256').update(await readFile(join(here,f))).digest('hex'),h);pass('PINNED_HASHES');
 await sql(await read('fixture_sql_engine_only.sql'));await server.start();
 proof.database=(await query('SELECT version() v'))[0].v;
 await run('preflight_read_only.sql','TENANT_RESUME_PREFLIGHT|PASS|none');pass('ACTUAL_PSQL_PREFLIGHT');
 await sql('ALTER TABLE public.candidate_documents DISABLE ROW LEVEL SECURITY');await run('forward_proposed.sql',null,3);await sql('ROLLBACK;ALTER TABLE public.candidate_documents ENABLE ROW LEVEL SECURITY');assert.equal((await query("SELECT to_regclass('private.candidate_resume_shares') p"))[0].p,null);pass('PREREQUISITE_FAILURE_NO_PARTIAL_WRITES');
 await run('forward_proposed.sql','TENANT_RESUME_REPAIR=COMMITTED');await run('postcheck_read_only.sql','TENANT_RESUME_POSTCHECK|PASS|none');pass('ACTUAL_PSQL_FORWARD_POSTCHECK');
 await run('forward_proposed.sql',null,3);await sql('ROLLBACK');pass('REPLAY_REJECTED');
 for(const [name,id] of Object.entries(user))await query('INSERT INTO auth.users(id,email) VALUES($1,$2)',[id,name+'@example.invalid']);
 for(const [name,id] of Object.entries(user))if(!['admin','staff'].includes(name))await query('INSERT INTO public.platform_users(user_id,account_type,display_name,email,account_status) VALUES($1,$2,$3,$4,$5)',[id,name.startsWith('co')?'company':name.startsWith('ct')?'contractor':'candidate','Synthetic '+name,name+'@example.invalid','active']);
 for(const name of ['admin','staff']){await query('INSERT INTO public.staff_profiles(user_id,display_name) VALUES($1,$2)',[user[name],'Synthetic '+name]);await query('INSERT INTO public.staff_roles(user_id,role) VALUES($1,$2)',[user[name],name==='admin'?'admin':'recruiter']);}
 for(const id of [co,coB])await query("INSERT INTO public.companies(id,legal_name,account_status) VALUES($1,'Synthetic Company','active')",[id]);
 for(const id of [ct,ctB])await query("INSERT INTO public.contractors(id,agency_name,account_status) VALUES($1,'Synthetic Contractor','active')",[id]);
 for(const [name,id,role] of [['coA',co,'owner'],['coB',coB,'owner'],['coViewer',co,'viewer']])await query("INSERT INTO public.company_users(company_id,user_id,role,status) VALUES($1,$2,$3,'active')",[id,user[name],role]);
 for(const [name,id,role] of [['ctA',ct,'owner'],['ctB',ctB,'owner'],['ctViewer',ct,'coordinator']])await query("INSERT INTO public.contractor_users(contractor_id,user_id,role,status) VALUES($1,$2,$3,'active')",[id,user[name],role]);
 for(const [id,u,phone] of [[cand,user.a,'9876549811'],[candB,user.b,'9876549812']])await query("INSERT INTO public.candidates(id,user_id,full_name,age,gender,mobile,current_location,district,state,highest_qualification,candidate_type,interview_available,consent,profile_status,profile_completion_status) VALUES($1,$2,'Synthetic Candidate',25,'Male',$3,'Sanand','Ahmedabad','Gujarat','ITI','Fresher','Yes',true,'active','complete')",[id,u,phone]);
 for(const [id,company,code] of [[req,co,'E2E-SHARE-1'],[ctReq,null,'E2E-SHARE-2'],[otherReq,coB,'E2E-SHARE-3']])await query("INSERT INTO public.employer_requirements(id,company_id,company_name,contact_person,mobile,company_location,job_role,required_headcount,consent,requirement_code) VALUES($1,$2,'Synthetic','Synthetic','9876549813','Sanand','Operator',2,true,$3)",[id,company,code]);
 await query("INSERT INTO public.requirement_contractors(requirement_id,contractor_id,assigned_headcount,origin_type,submission_status,assignment_status) VALUES($1,$2,2,'contractor_submission','approved','active')",[ctReq,ct]);
 for(const [id,c,r] of [[app,cand,req],[ctApp,cand,ctReq],[otherApp,candB,otherReq]])await query('INSERT INTO public.candidate_applications(id,candidate_id,requirement_id) VALUES($1,$2,$3)',[id,c,r]);
 await query("INSERT INTO storage.objects(id,bucket_id,name,owner,version) VALUES($1,'candidate-private',$2,$3,'v1')",[obj,objectName,user.a]);
 for(const [id,type,path] of [[doc,'resume',objectName],[pan,'pan',user.a+'/'+pan+'/pan.pdf']])await query("INSERT INTO public.candidate_documents(id,candidate_id,document_type,storage_object_name,display_file_name,mime_type,file_size_bytes) VALUES($1,$2,$3,$4,'synthetic.pdf','application/pdf',128)",[id,cand,type,path]);
 await as(user.a);await denied('SELECT public.set_candidate_resume_consent($1,$2,$3,$4,true)',[otherApp,doc,'company',coB]);await denied('SELECT public.set_candidate_resume_consent($1,$2,$3,$4,true)',[app,pan,'company',co]);await denied('SELECT public.set_candidate_resume_consent($1,$2,$3,$4,true)',[app,doc,'company',coB]);pass('CANDIDATE_OTHER_APPLICATION_WRONG_RECIPIENT_NONRESUME_DENIED');
 await consent();await consent();await as(user.coA);assert.equal((await list()).length,0);assert.equal((await storage()).length,0);pass('CONSENT_ALONE_DOES_NOT_SHARE');
 await as(user.admin);let row=await shareRecord();await denied('SELECT public.admin_set_application_resume_share($1,$2,true)',[row.consent_id,row.revision]);await review('under_verification');await review('verified');await setShare(row);await setShare(row);pass('ADMIN_VERIFIED_SHARE_AND_IDEMPOTENCE');
 await as(user.coA);assert.equal((await list()).length,1);assert.equal((await storage()).length,1);assert.equal((await query('SELECT * FROM public.get_shared_application_resume_access($1,$2,$3)',[app,doc,'company'])).length,1);assert.equal((await query('SELECT * FROM public.get_shared_application_resume_access($1,$2,$3)',[app,pan,'company'])).length,0);pass('COMPANY_OWN_SHARED_RESUME_AND_STORAGE_SELECT');
 assert.equal((await query('UPDATE storage.objects SET name=$1 WHERE name=$2 RETURNING name',['bad',objectName])).length,0);assert.equal((await query('DELETE FROM storage.objects WHERE name=$1 RETURNING name',[objectName])).length,0);assert.equal((await storage()).length,1);await denied("INSERT INTO storage.objects(bucket_id,name) VALUES('candidate-private',$1)",[user.a+'/new/other.pdf'],'42501');pass('TENANT_CANNOT_INSERT_OVERWRITE_OR_DELETE');
 await as(user.coB);assert.equal((await list()).length,0);assert.equal((await storage()).length,0);
 for(const name of ['coViewer','ctViewer','b','staff']){await as(user[name]);await denied('SELECT * FROM public.get_shared_application_resume($1,$2)',[app,'company']);await denied('SELECT public.admin_set_application_resume_share($1,$2,true)',[row.consent_id,row.revision]);}
 await as('','anon');await denied('SELECT * FROM public.get_shared_application_resume($1,$2)',[app,'company'],'42501');pass('CROSS_TENANT_VIEWER_COORDINATOR_NONADMIN_ANON_DENIED');
 await as(user.coA);await denied('SELECT * FROM private.candidate_resume_shares',[],'42501');await denied('SELECT * FROM public.candidate_documents',[],'42501');await denied('SELECT private.resume_sharing_context($1)',[app],'42501');pass('NO_DIRECT_TABLE_OR_INTERNAL_HELPER_ACCESS');
 await as(user.admin);await setShare(row,false);await as(user.coA);assert.equal((await list()).length,0);assert.equal((await storage()).length,0);pass('ADMIN_REVOCATION_STOPS_FUTURE_ACCESS');
 await as(user.admin);await setShare(row);await as(user.a);await consent(app,doc,'company',co,false);await as(user.coA);assert.equal((await list()).length,0);assert.equal((await storage()).length,0);await as(user.admin);await denied('SELECT public.admin_set_application_resume_share($1,$2,true)',[row.consent_id,row.revision]);pass('CONSENT_REVOCATION_AND_STALE_ADMIN_REQUEST_DENIED');
 await as(user.a);await consent();await as(user.coA);assert.equal((await list()).length,0);await as(user.admin);row=await shareRecord();await setShare(row);pass('RECONSENT_REQUIRES_FRESH_ADMIN_SHARE');
 await as(user.a);await consent(ctApp,doc,'contractor',ct);await as(user.ctA);assert.equal((await list(ctApp,'contractor')).length,0);await as(user.admin);const ctRow=await shareRecord(ctApp,'contractor');await setShare(ctRow);await as(user.ctA);assert.equal((await list(ctApp,'contractor')).length,1);assert.equal((await storage()).length,1);await as(user.ctB);assert.equal((await list(ctApp,'contractor')).length,0);pass('CONTRACTOR_DISTINCT_CONSENT_AND_ADMIN_SHARE');
 await sql('RESET ROLE');await query("UPDATE public.company_users SET status='suspended' WHERE user_id=$1",[user.coA]);await as(user.coA);await denied('SELECT * FROM public.get_shared_application_resume($1,$2)',[app,'company']);assert.equal((await storage()).length,0);await sql('RESET ROLE');await query("UPDATE public.company_users SET status='active' WHERE user_id=$1",[user.coA]);
 await query("UPDATE public.candidates SET status='inactive' WHERE id=$1",[cand]);await as(user.coA);assert.equal((await list()).length,0);assert.equal((await storage()).length,0);await sql('RESET ROLE');await query("UPDATE public.candidates SET status='new' WHERE id=$1",[cand]);pass('SUSPENDED_MEMBERSHIP_AND_INACTIVE_CANDIDATE_DENIED');
 await query("UPDATE public.candidate_applications SET application_status='cancelled' WHERE id=$1",[app]);await as(user.coA);assert.equal((await list()).length,0);await sql('RESET ROLE');await query("UPDATE public.candidate_applications SET application_status='applied' WHERE id=$1",[app]);await query("UPDATE public.requirement_contractors SET submission_status='closed' WHERE requirement_id=$1",[ctReq]);await as(user.ctA);assert.equal((await list(ctApp,'contractor')).length,0);await sql('RESET ROLE');await query("UPDATE public.requirement_contractors SET submission_status='approved' WHERE requirement_id=$1",[ctReq]);pass('APPLICATION_AND_CONTRACTOR_LINK_ACCESS_BOUNDARIES');
 await query("UPDATE storage.objects SET version='v2',updated_at=now() WHERE id=$1",[obj]);await as(user.coA);assert.equal((await list()).length,0);assert.equal((await storage()).length,0);await as(user.admin);await denied('SELECT public.admin_set_application_resume_share($1,$2,true)',[row.consent_id,row.revision]);await as(user.a);await consent();await as(user.admin);row=await shareRecord();await setShare(row);pass('OBJECT_REPLACEMENT_REQUIRES_NEW_CONSENT_AND_SHARE');
 await sql('RESET ROLE');await query('UPDATE public.candidate_documents SET active=false,replaced_at=now() WHERE id=$1',[doc]);await query("INSERT INTO public.candidate_documents(id,candidate_id,document_type,storage_object_name,display_file_name,mime_type,file_size_bytes) VALUES($1,$2,'resume',$3,'new.pdf','application/pdf',128)",[replacement,cand,user.a+'/'+replacement+'/new.pdf']);await as(user.coA);assert.equal((await list()).length,0);assert.equal((await storage()).length,0);pass('NEW_DOCUMENT_DOES_NOT_INHERIT_OLD_SHARE');
 await sql('RESET ROLE');const audits=await query("SELECT actor_type,metadata FROM public.audit_logs WHERE entity_type='resume_share'");assert.equal(audits.length,11);for(const a of audits)assert.ok(Object.keys(a.metadata).every(k=>['allowed','version','shared'].includes(k)));const count=(await query('SELECT count(*) n FROM private.candidate_resume_shares'))[0].n;assert.equal(count,2);pass('AUDIT_MINIMIZATION_AND_DUPLICATE_GRANT_INVARIANT');
 await run('postcheck_read_only.sql','TENANT_RESUME_POSTCHECK|PASS|none');await run('rollback_guarded.sql','TENANT_RESUME_ROLLBACK=COMMITTED');assert.equal((await query('SELECT count(*) n FROM private.candidate_resume_shares'))[0].n,count);assert.equal((await query("SELECT count(*) n FROM public.audit_logs WHERE entity_type='resume_share'"))[0].n,audits.length);pass('GUARDED_ROLLBACK_RETAINS_CONSENT_AND_AUDIT');
 proof.result='PASS';
}catch(e){proof.result='FAIL';proof.error={message:e.message.slice(0,3000),code:e.code,where:e.where};console.error(JSON.stringify(proof.error));process.exitCode=1;}
finally{await server.stop();await db.close();await writeFile(join(here,'local_validation.json'),JSON.stringify(proof,null,2)+'\n');}
