BEGIN READ ONLY;
SET LOCAL statement_timeout='30s';
DO $post$ DECLARE failed text; BEGIN
WITH checks AS (
SELECT 'private.rotate_onboarding_share_revision()' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('private.rotate_onboarding_share_revision()') AND md5(p.prosrc)='cca5cd93e0b37774e831bca8c52757a6' AND p.prosecdef AND p.provolatile='v' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=false) ok
UNION ALL
SELECT 'public.update_candidate_onboarding_details(text,text,text,text,boolean,text,boolean,text)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.update_candidate_onboarding_details(text,text,text,text,boolean,text,boolean,text)') AND md5(p.prosrc)='2c3d9fddfb01b2c77c176e880798dde3' AND p.prosecdef AND p.provolatile='v' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'private.application_sharing_candidate_active(uuid,uuid)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('private.application_sharing_candidate_active(uuid,uuid)') AND md5(p.prosrc)='b4edf1ea12ded087af3c77f71f515cfa' AND p.prosecdef AND p.provolatile='s' AND l.lanname='sql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=false) ok
UNION ALL
SELECT 'private.application_sharing_items(uuid)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('private.application_sharing_items(uuid)') AND md5(p.prosrc)='8ea5ea8e3ebc5eec17dfa3398c1ce72c' AND p.prosecdef AND p.provolatile='s' AND l.lanname='sql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=false) ok
UNION ALL
SELECT 'private.resume_share_effective(uuid)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('private.resume_share_effective(uuid)') AND md5(p.prosrc)='f377e9c0959270c5b94c7aca1e02541e' AND p.prosecdef AND p.provolatile='s' AND l.lanname='sql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=false) ok
UNION ALL
SELECT 'private.application_document_sharing_context(uuid)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('private.application_document_sharing_context(uuid)') AND md5(p.prosrc)='bc140739b510a494f7f2cc28ad2f3b5b' AND p.prosecdef AND p.provolatile='s' AND l.lanname='sql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=false) ok
UNION ALL
SELECT 'public.admin_list_application_document_sharing(uuid)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.admin_list_application_document_sharing(uuid)') AND md5(p.prosrc)='8257366389dccaad9426b7ec0414739b' AND p.prosecdef AND p.provolatile='s' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'public.get_candidate_document_sharing(text)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.get_candidate_document_sharing(text)') AND md5(p.prosrc)='bb6c9c313e3580dfc005801890a331c7' AND p.prosecdef AND p.provolatile='s' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'public.admin_set_application_document_share(uuid,text,text,uuid,text,uuid,boolean)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.admin_set_application_document_share(uuid,text,text,uuid,text,uuid,boolean)') AND md5(p.prosrc)='72a7b3d2e49ca36f72df46c1640bd777' AND p.prosecdef AND p.provolatile='v' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'public.get_shared_application_items(uuid,text)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.get_shared_application_items(uuid,text)') AND md5(p.prosrc)='9f4ad069ffcb8e23bf13cba6870ea97d' AND p.prosecdef AND p.provolatile='s' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'public.get_shared_application_document_access(uuid,uuid,text)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.get_shared_application_document_access(uuid,uuid,text)') AND md5(p.prosrc)='4e45a889a3b9d1773edfc859dd0be0a3' AND p.prosecdef AND p.provolatile='s' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'private.application_joining_detail(uuid,text)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('private.application_joining_detail(uuid,text)') AND md5(p.prosrc)='92b6e5798c79fcc717e8b64c071f61cb' AND p.prosecdef AND p.provolatile='s' AND l.lanname='sql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=false) ok
UNION ALL
SELECT 'public.admin_get_application_joining_detail(uuid,text)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.admin_get_application_joining_detail(uuid,text)') AND md5(p.prosrc)='022862b78e73d98ac6f8187975850b07' AND p.prosecdef AND p.provolatile='s' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'public.get_shared_application_joining_detail(uuid,text,text)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.get_shared_application_joining_detail(uuid,text,text)') AND md5(p.prosrc)='ceec3745eabcc93a43d69bd47f154a12' AND p.prosecdef AND p.provolatile='s' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'public.set_candidate_resume_consent(uuid,uuid,text,uuid,boolean)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.set_candidate_resume_consent(uuid,uuid,text,uuid,boolean)') AND md5(p.prosrc)='8a13645564ecdd45d81bec4c3240b1fd' AND p.prosecdef AND p.provolatile='v' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'public.admin_set_application_resume_share(uuid,uuid,boolean)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.admin_set_application_resume_share(uuid,uuid,boolean)') AND md5(p.prosrc)='a8cf853114b0d7115870fbd5c1d26205' AND p.prosecdef AND p.provolatile='v' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'public.get_shared_application_resume(uuid,text)' name,EXISTS(SELECT 1 FROM pg_proc p JOIN pg_language l ON l.oid=p.prolang WHERE p.oid=to_regprocedure('public.get_shared_application_resume(uuid,text)') AND md5(p.prosrc)='1aec9de203627d8e7fb36b8ef808b2e6' AND p.prosecdef AND p.provolatile='s' AND l.lanname='plpgsql' AND pg_get_userbyid(p.proowner)='postgres' AND (p.proconfig @> ARRAY['search_path='] OR p.proconfig @> ARRAY['search_path=""']) AND NOT has_function_privilege('anon',p.oid,'EXECUTE') AND has_function_privilege('authenticated',p.oid,'EXECUTE')=true) ok
UNION ALL
SELECT 'private.resume_application_recipients(uuid)',EXISTS(SELECT 1 FROM pg_proc WHERE oid=to_regprocedure('private.resume_application_recipients(uuid)') AND md5(prosrc)='e044e66d076088aef544e6b9ad4830ee' AND prosecdef AND pg_get_userbyid(proowner)='postgres' AND NOT has_function_privilege('anon',oid,'EXECUTE') AND has_function_privilege('authenticated',oid,'EXECUTE')=false)
UNION ALL
SELECT 'private.current_resume_recipient(text)',EXISTS(SELECT 1 FROM pg_proc WHERE oid=to_regprocedure('private.current_resume_recipient(text)') AND md5(prosrc)='18d8c3b5e8f57a7a745e9218015ca6a4' AND prosecdef AND pg_get_userbyid(proowner)='postgres' AND NOT has_function_privilege('anon',oid,'EXECUTE') AND has_function_privilege('authenticated',oid,'EXECUTE')=false)
UNION ALL
SELECT 'private.can_read_shared_candidate_resume(text)',EXISTS(SELECT 1 FROM pg_proc WHERE oid=to_regprocedure('private.can_read_shared_candidate_resume(text)') AND md5(prosrc)='3a3f6d9d12b973f9be19ee459316aee5' AND prosecdef AND pg_get_userbyid(proowner)='postgres' AND NOT has_function_privilege('anon',oid,'EXECUTE') AND has_function_privilege('authenticated',oid,'EXECUTE')=true)
UNION ALL
SELECT 'private_grants',EXISTS(SELECT 1 FROM pg_class WHERE oid=to_regclass('private.candidate_resume_shares') AND relrowsecurity) AND NOT has_any_column_privilege('authenticated','private.candidate_resume_shares','SELECT,INSERT,UPDATE,REFERENCES') AND NOT has_any_column_privilege('anon','private.candidate_resume_shares','SELECT,INSERT,UPDATE,REFERENCES')
UNION ALL
SELECT 'onboarding_rls_acl',EXISTS(SELECT 1 FROM pg_class WHERE oid=to_regclass('public.candidate_onboarding_details') AND relrowsecurity) AND NOT has_any_column_privilege('authenticated','public.candidate_onboarding_details','SELECT,INSERT,UPDATE,REFERENCES') AND NOT has_any_column_privilege('anon','public.candidate_onboarding_details','SELECT,INSERT,UPDATE,REFERENCES')
UNION ALL
SELECT 'new_constraints',(SELECT count(*)=4 AND bool_and(convalidated) FROM pg_constraint WHERE (conrelid=to_regclass('private.candidate_resume_shares') AND conname IN ('candidate_sharing_mode_check','candidate_sharing_item_check','candidate_sharing_item_unique')) OR (conrelid=to_regclass('public.candidate_onboarding_details') AND conname='candidate_onboarding_full_account_check'))
UNION ALL
SELECT 'onboarding_revision_trigger',EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid=to_regclass('public.candidate_onboarding_details') AND tgname='candidate_onboarding_sharing_revision' AND tgenabled='O' AND tgfoid=to_regprocedure('private.rotate_onboarding_share_revision()'))
UNION ALL
SELECT 'storage_recipient_policy',EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND policyname='Recipients read Admin shared resumes' AND cmd='SELECT' AND roles=ARRAY['authenticated']::name[] AND qual='((bucket_id = ''candidate-private''::text) AND private.can_read_shared_candidate_resume(name))')
) SELECT string_agg(name,',' ORDER BY name) INTO failed FROM checks WHERE NOT coalesce(ok,false);
IF failed IS NOT NULL THEN RAISE EXCEPTION 'Document sharing postcheck mismatch: %',failed; END IF; END $post$;
SELECT 'ADMIN_DOCUMENT_POSTCHECK=PASS';
ROLLBACK;
